- AIInterviewBot/AIInterviewBot/settings.py
- AIInterviewBot/AIInterviewBot/urls.py
- AIInterviewBot/accounts/forms.py
- AIInterviewBot/accounts/views.py
- AIInterviewBot/static/css/accounts.css
- AIInterviewBot/templates/accounts/register.html
- requirements.txt
1.新增註冊頁面(新增forms包括登入表單)
1.1 安裝django-simple-captcha 驗證碼套件
1.2 驗證碼設定加入設定檔
2.新增accounts base css
> feature-RegisterPage

- AIInterviewBot/templates/accounts/index.html
> feature-HomePage

- AIInterviewBot/AIInterviewBot/urls.py
- AIInterviewBot/accounts/views.py
- AIInterviewBot/templates/accounts/email_error.html
- AIInterviewBot/templates/accounts/email_success.html
- AIInterviewBot/templates/accounts/forgot_password.html
feature-ForgotPassword
1.新增忘記密碼頁面
2.新增電子郵件錯誤及成功頁面
> feature-ForgotPassword

- AIInterviewBot/AIInterviewBot/settings.py
- AIInterviewBot/AIInterviewBot/urls.py
- AIInterviewBot/accounts/views.py
- AIInterviewBot/templates/accounts/login.html
> feature-LoginPage

- AIInterviewBot/accounts/views.py
- AIInterviewBot/templates/accounts/reset_password_complete.html
- AIInterviewBot/templates/accounts/reset_password_confirm.html
1.新增密碼重設成功的頁面
2.新增使用者收信後的連結頁
3.新增view.py的功能密碼重設和密碼收信
> feature-PasswordComfirmComplete

- AIInterviewBot/AIInterviewBot/settings.py
- AIInterviewBot/AIInterviewBot/urls.py
- AIInterviewBot/accounts/forms.py
- AIInterviewBot/accounts/views.py
- AIInterviewBot/static/css/accounts.css
- AIInterviewBot/templates/accounts/email_error.html
- AIInterviewBot/templates/accounts/email_success.html
- AIInterviewBot/templates/accounts/forgot_password.html
- AIInterviewBot/templates/accounts/login.html
- AIInterviewBot/templates/accounts/register.html
- AIInterviewBot/templates/accounts/reset_password_complete.html
- AIInterviewBot/templates/accounts/reset_password_confirm.html
1.修正urls merge syntax error
2.修正登入按鈕文字原為"送出"
3.HTML form tag 改成使用form的label
4.輸入框focus讓label往上跑 accounts.css
5.驗證碼setting改回預設大小
6.新增ForgotPasswordForm
7.加上<a href>的路由
8.新增重設密碼確認及完成urls
9.更新boostrap到最新版
10.修正accounts.css <link>
> bugfix-SyntaxOptimize

- AIInterviewBot/templates/base.html
Reverts THChen2002/AI-Interview-Bot#15
> feature-BaseHtml

- AIInterviewBot/templates/base.html
1.讓Menu三條線在navbar的左邊
2.更改觸發按鈕樣式
3.確認Menu展開的寬度
> bugfix-BaseHtmlSideMenu

- AIInterviewBot/accounts/views.py
1.將view.py檔中#修改密碼 form改為changePasswordForm
> bugfix-修正change_password

- AIInterviewBot/templates/basic_info.html
1.html第4-5行沒用到記得刪掉
2.刪除<script>標籤
> feature-Basic_info

- AIInterviewBot/templates/accounts/AccountsBase.html
- AIInterviewBot/templates/accounts/login.html
1.修正merge問題
2.修正AccountsBase的JQ引入位置(head)
> bugfix-LoginPage&AccountsBase

- AIInterviewBot/AIInterviewBot/settings.py
- AIInterviewBot/accounts/admin.py
- AIInterviewBot/accounts/models.py
1.新建User Model
不要使用內建的User
改成使用繼承AbstractUser
> feature-UserModel

- AIInterviewBot/accounts/admin.py
1.更新AccountAdmin的display,search,filter
> feature-UpdateAccountAdmin

- AIInterviewBot/AIInterviewBot/settings.py
- AIInterviewBot/contents/admin.py
- AIInterviewBot/contents/apps.py
- AIInterviewBot/contents/models.py
- AIInterviewBot/contents/tests.py
- AIInterviewBot/contents/views.py
1.新增Contents app
2.OPENAI_API_KEY加入Settings
> feature-initContentsAPP

- AIInterviewBot/AIInterviewBot/urls.py
- AIInterviewBot/accounts/views.py
- AIInterviewBot/contents/forms.py
- AIInterviewBot/contents/views.py
- AIInterviewBot/templates/contents/self_introduction.html
> feature-SelfIntroductionPage

- AIInterviewBot/contents/service.py
- AIInterviewBot/contents/views.py
- AIInterviewBot/templates/accounts/login.html
- AIInterviewBot/templates/contents/self_introduction.html
1.定義連線OpenAI方法(可以取得結果)
2.自我介紹views的msg先寫死
> feature-OpenAI

- AIInterviewBot/AIInterviewBot/urls.py
- AIInterviewBot/contents/forms.py
- AIInterviewBot/contents/views.py
- AIInterviewBot/templates/accounts/index.html
- AIInterviewBot/templates/contents/cover_letter.html
- AIInterviewBot/templates/contents/mock_interview.html
- AIInterviewBot/templates/contents/recommendation_letter.html
- AIInterviewBot/templates/contents/resume.html
1.新增頁面-求職信、推薦信、簡歷、模擬面試
2.建表單-求職信、推薦信、簡歷、模擬面試
3.新增首頁連結到各個頁面
4.刪除content裡的id
> feature-ContentPage

- AIInterviewBot/templates/base.html
> bugfix-BaseLogoCenter

- AIInterviewBot/AIInterviewBot/urls.py
- AIInterviewBot/contents/views.py
- AIInterviewBot/static/css/base.css
- AIInterviewBot/static/css/progresscircle.css
- AIInterviewBot/static/js/progresscircle.js
- AIInterviewBot/templates/base.html
- AIInterviewBot/templates/contents/dashboard.html
> feature-DashboardPage

- AIInterviewBot/accounts/forms.py
- AIInterviewBot/accounts/views.py
- AIInterviewBot/templates/accounts/register.html
- AIInterviewBot/templates/accounts/reset_password_confirm.html
1.新增註冊功能
2.確認忘記密碼流程
3.修正更改密碼版面
> feature-AccountsProcess

- AIInterviewBot/templates/accounts/register.html
> bugfix-AccountsCSS

- AIInterviewBot/AIInterviewBot/urls.py
- AIInterviewBot/contents/forms.py
- AIInterviewBot/contents/views.py
- AIInterviewBot/static/css/base.css
- AIInterviewBot/templates/contents/mock_interview.html
1.新增css樣式
2.修改模擬面試頁面
3.跳轉到單選多選的頁面
> feature-MockInterviewCss

- AIInterviewBot/templates/contents/mock_interview_mode.html
> MockInterview

- AIInterviewBot/contents/service.py
- AIInterviewBot/contents/views.py
1.將messages拉到Service用成function
2.修正其他的form和hml
> feature-ServicePrompt

- AIInterviewBot/contents/forms.py
- AIInterviewBot/templates/contents/cover_letter.html
- AIInterviewBot/templates/contents/mock_interview.html
- AIInterviewBot/templates/contents/recommendation_letter.html
- AIInterviewBot/templates/contents/resume.html
- AIInterviewBot/templates/contents/self_introduction.html
> faeture-ContentCss

- AIInterviewBot/AIInterviewBot/settings.py
- AIInterviewBot/accounts/forms.py
- AIInterviewBot/accounts/views.py
1.修正同email能夠重複註冊的問題
2.修正Google端登入無法抓到email和頭貼
3.修正Google帳號重複寫入的問題
> bugfix-AccountsProcess&GoogleLogin

- AIInterviewBot/accounts/views.py
- AIInterviewBot/templates/accounts/register.html
- AIInterviewBot/templates/modal_template.html
> bugfix-accounts

- AIInterviewBot/accounts/views.py
- AIInterviewBot/templates/accounts/forgot_password.html
- AIInterviewBot/templates/accounts/reset_password_confirm.html
> bugfix-resetPasswordModal

- AIInterviewBot/accounts/forms.py
- AIInterviewBot/accounts/views.py
- AIInterviewBot/templates/accounts/change_password.html
- AIInterviewBot/templates/base.html
> feature-ChangePassword

- AIInterviewBot/contents/service.py
- AIInterviewBot/contents/views.py
> feature-ResumeDownload

- AIInterviewBot/AIInterviewBot/urls.py
- AIInterviewBot/accounts/views.py
- AIInterviewBot/templates/accounts/help_center.html
- AIInterviewBot/templates/base.html
> feature-HelpPage

- AIInterviewBot/AIInterviewBot/urls.py
- AIInterviewBot/contents/forms.py
- AIInterviewBot/contents/service.py
- AIInterviewBot/contents/templatetags/filter.py
- AIInterviewBot/contents/views.py
- AIInterviewBot/templates/contents/mock_interview_mode.html
- AIInterviewBot/templates/contents/mock_interview_result.html
1.完成模擬面試流程功能(評分未完成)
2.送出面試結果後寫入InterviewRecord、InterviewScore
3.成功後跳傳至結果頁面
4.修復get_messages()
5.修正單題多題文字
6.修復MockInterviewForm重複問題
7.新增templatetags
> feature-MockInterviewFlow

- AIInterviewBot/AIInterviewBot/urls.py
- AIInterviewBot/accounts/views.py
- AIInterviewBot/templates/accounts/personal.html
> feature-PersonalPage

- AIInterviewBot/AIInterviewBot/urls.py
- AIInterviewBot/contents/views.py
- AIInterviewBot/templates/base.html
- AIInterviewBot/templates/contents/dashboard.html
1.新增sidebar儀錶板按鈕
2.移除帳戶設定超連結
3.帶入資料庫資訊
4.新增get_chart_data() api給前端call
> feature-Dashboard

- AIInterviewBot/accounts/forms.py
- AIInterviewBot/static/css/accounts.css
- AIInterviewBot/templates/accounts/forgot_password.html
- AIInterviewBot/templates/accounts/register.html
- AIInterviewBot/templates/contents/cover_letter.html
- AIInterviewBot/templates/contents/mock_interview.html
- AIInterviewBot/templates/contents/recommendation_letter.html
- AIInterviewBot/templates/contents/resume.html
- AIInterviewBot/templates/contents/self_introduction.html
1.調整頁面寬度
2.修改密碼、註冊帳號字套用css(點擊往上)
> feature-FixCss

- AIInterviewBot/AIInterviewBot/urls.py
- AIInterviewBot/accounts/forms.py
- AIInterviewBot/accounts/views.py
- AIInterviewBot/templates/accounts/problem_report.html
- AIInterviewBot/templates/base.html
> feature-ProblemReportPage

- AIInterviewBot/static/css/accounts.css
> bugfix-RegisterLabel

- AIInterviewBot/AIInterviewBot/urls.py
- AIInterviewBot/accounts/views.py
- AIInterviewBot/static/css/base.css
- AIInterviewBot/templates/accounts/history.html
- AIInterviewBot/templates/base.html
> feature-HistoryPage

- AIInterviewBot/AIInterviewBot/settings.py
- AIInterviewBot/accounts/custom_validator.py
- AIInterviewBot/accounts/forms.py
- AIInterviewBot/accounts/views.py
> feature-ChineseErrorMessage

- AIInterviewBot/contents/views.py
- AIInterviewBot/templates/contents/mock_interview_result.html
> feature-MockInterviewResult

- AIInterviewBot/contents/forms.py
1.Textarea固定大小(不能拉)
'style':'resize:none;'
2.確定行數列數
> feature-TextareaFix

- AIInterviewBot/contents/forms.py
- AIInterviewBot/contents/service.py
- AIInterviewBot/contents/views.py
- AIInterviewBot/templates/contents/resume.html
1.根據使用者輸入生成對應的簡歷表
export_resume()
2.更新簡歷輸入頁面與figma相同
> feature-Resume

- AIInterviewBot/templates/contents/dashboard.html
> feature-DashBoardChart

- AIInterviewBot/templates/contents/mock_interview.html
> feature-MockInterviewLoading

- AIInterviewBot/static/css/changePassword.css
- AIInterviewBot/templates/accounts/change_password.html
- AIInterviewBot/templates/accounts/email_error.html
- AIInterviewBot/templates/accounts/email_success.html
- AIInterviewBot/templates/accounts/forgot_password.html
- AIInterviewBot/templates/accounts/login.html
- AIInterviewBot/templates/accounts/register.html
- AIInterviewBot/templates/accounts/reset_password_confirm.html
1.立即註冊拿掉底線
2.登入相關頁面框陰影調整
3.登入部分頁面字體調整
4.修改密碼繼承base
5.Logo調整成與Figma相同
6.change_password輸入框label點擊上移
> bugfix-Login

- AIInterviewBot/templates/contents/resume.html
> feature-HistoryResult

- AIInterviewBot/accounts/forms.py
- AIInterviewBot/static/css/help_center.css
- AIInterviewBot/static/css/problem_report.css
- AIInterviewBot/templates/accounts/forgot_password.html
- AIInterviewBot/templates/accounts/help_center.html
- AIInterviewBot/templates/accounts/login.html
- AIInterviewBot/templates/accounts/problem_report.html
- AIInterviewBot/templates/accounts/register.html
- AIInterviewBot/templates/contents/history.html
1.修正網頁index"使用者登入"位置
2.幫助中心、回報問題、歷史紀錄統一格式
3.登入相關頁面LOGO
4.問題回報、回報問題單獨CSS
> feature-UniteCSS

- AIInterviewBot/templates/accounts/reset_password_confirm.html
> feature-DeleteHelpContext

- AIInterviewBot/contents/views.py
> bugfix-MonthFilter

- AIInterviewBot/templates/accounts/index.html
- AIInterviewBot/templates/contents/dashboard.html
> bugfix-BarChart
